# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=2.1.0
maven_group=com.joshiegemfinder.synchronisedblockstates
archives_base_name=synchronised-blockstates

# Network remapping
network_namespace=named
fabric_runtime_namespace=intermediary
forge_runtime_namespace=searge

# Dependencies
fabric_version=0.92.7+1.20.1