
buildscript {
	// load properties	
	Properties properties = new Properties()
	FileInputStream input = new FileInputStream(file('../gradle.properties'))
	properties.load(input)
	input.close()
	
	for(String key : properties.stringPropertyNames()) {
		ext.set(key, properties.getProperty(key))
	}

	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
	// necessary for the RemapJarTask import
    dependencies {
    	classpath "net.fabricmc:fabric-loom:${loom_version}"
    }
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	mavenCentral()
}

dependencies {
	implementation "net.fabricmc:fabric-loom:${loom_version}"
}